'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
  HandWrite:
    uses: script@v1
    with:
      image: tensorflow/tensorflow:1.14.0-gpu-py3
      script: |-
        cd /input/handwrite
        python pretrained-model.py
    needs:
      - Clonerepo
    inputs:
      handwrite: CloneRepo.outputs.repo
    outputs:
      modelHandwrite:
        type: dataset
        with:
          ref: model-handwrite
    resources:
      instance-type: C5
context:
  event:
    github:
      ref: 0defa7bfb8a4d2b69640c45332bf43be09739d8c
      url: https://github.com/chicuongdx/Handwrite
