'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
  HandWrite:
    needs:
      - Clonerepo
    inputs:
      handwrite: CloneRepo.outputs.repo
    outputs:
      modelHandwrite:
        type: dataset
        with:
          ref: model-handwrite
    resources:
      instance-type: C5
    uses: script@v1
    with:
      image: tensorflow/tensorflow:1.14.0-gpu-py3
      script: |-
        pip install sklearn
        cd /input/handwrite
        python pretrained-model.py
